spring:
  application:
    name: kids-bank-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://db:5432/bank
#    url: jdbc:postgresql://localhost:5800/bank
    username: bank
    password: bank
    driver-class-name: org.postgresql.Driver

app:
  auth:
    secret: a45933b42fc4f16f67902829ab2c259205f3080e672c1695beee0f68b915c579fedc4b37737062bd
    access-life-time: 900000
    refresh-life-time: 2592000000

server:
  port: 3567
